#!/bin/bash
set -e

# Figure out where this script is located.
SELFDIR="`dirname \"$0\"`"
SELFDIR="`cd \"$SELFDIR\" && pwd`"

# Tell Bundler where the Gemfile and gems are.
export BUNDLE_GEMFILE="$SELFDIR/lib/vendor/Gemfile"
unset BUNDLE_IGNORE_CONFIG

# Run the actual app using the bundled Ruby interpreter, with Bundler activated.
# exec "ruby jekyll build"
$SELFDIR/lib/ruby/bin/ruby -rbundler/setup $SELFDIR/lib/vendor/ruby/2.1.0/bin/jekyll build -s ./jekyll/jekyll-site -d /tmp/_site
ls /tmp/_site
cat /tmp/_site/index.html
# exec "$SELFDIR/lib/ruby/bin/ruby" -rbundler/setup "$SELFDIR/lib/app/hello.rb"

# exec "$SELFDIR/lib/ruby/bin/ruby" -rbundler/setup "$SELFDIR/lib/vendor/ruby/2.1.0/bin/jekyll"
